### ISSUE TITLE
0.8.0 Release Timeline

### ISSUE THREAD

**Issue by theckman** [rabbitmq/rabbitmq-autocluster#28]
Hello,

I saw this comment indicating that a 0.8.0 release of this plugin was coming soon:

* https://github.com/rabbitmq/rabbitmq-autocluster/pull/23#issuecomment-300006562

Do you have an ETA for when a binary build of 0.8.0 may be available, as we're looking to use functionality introduced in that version. Also, will `3.6.9` be supported in the `0.8.0` release?

Cheers!

**Comment by theckman** [comment]
I just noticed #25. If possible, could its changes also be included in 0.8.0's release? I can see the problem it fixes causing us some issues.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions fofor potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
0.8.0 RC can ship when #6 (90% of the effort), #22 and #25 are merged. Should be some time next week.

**Comment by theckman** [comment]
@michaelklishin Thank you for replying back to me. I opened this issue so that it makes it easier for users to find more information about the 0.8.0 release as 0.7.0 isn't functional in a Kubernetes environment, which was a show-stopper for us. It's also a small enough project that I assumed one issue among the other one or two would make it extremely easy for others to find the information I was looking for.

This repo seems to have no information about the mailing list, or other channels of support, unless I missed it. Are end users of this plugin expected to discover the mailing list on their own, to then try and search for a discussion around d this plugin's release cadence?

Would you be willing to enhance the README so users are able to discover the proper support channels a bit easier? I'll happily open a thread on the mailing list later to ask about the possibility of re-jiggering the 0.8.0 release to only include Kube fixes, if the Consul stuff hits any unexpected delays.

**Comment by michaelklishin** [comment]
@theckman all projects under github.com/rabbitmq use the same mailing list: [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). We can add a README note to every single repository but there are 50+ of them and FWIW the list is mentioned on the home page of rabbitmq.com. On top of that there are typically 2 long lived branches under development, which means it's less trivial than it sounds :) I'm not against doing that, though.

Speaking of 0.8.0, I'm happy to release a milestone build within an hour for you to use (or at least test). An RC should follow as soon as #22 is merged. Would that work for you?

**Comment by michaelklishin** [comment]
@theckman [0.8.0.M1](https://github.com/rabbitmq/rabbitmq-autocluster/releases/tag/0.8.0-milestone1) is up on GitHub. Let us know how it goes either on the mailing list or by filing an issue (if there's enough information to clearly formulate what the root cause is).
