### ISSUE TITLE
plugin not detected on ubuntu 18.04, rabbitmq 3.6.10

### ISSUE THREAD

**Issue by monemihir** [rabbitmq/rabbitmq-autocluster#70]
Hi,

I'm running Ubuntu 18.04 with RabbitMQ 3.6.10.

I have tried copying the `*.ez` files to `/usr/lib/rabbitmq/plugins` (this folder does not exist on default `apt` install. I have also tried copying the `*.ez` files to `/usr/lib/rabbitmq/plugins/rabbitmq_server-3.6.10/plugins` folder.

In both instances when I run `rabbitmq-plugins list` the plugins don't show up in the list which mean when I run the `rabbitmq-plugins enable` command it fails.

Is there something I'm missing? I have tried for v0.10.0 and v0.8.0 of the plugins.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Plugin installation directory will vary between installation methods and can be [overridden](http://www.rabbitmq.com/relocate.html). It can be a list of colon-separated paths. Specifically on Linux `/usr/lib/rabbitmq/plugins` is always [prepended as of 3.6.7](https://github.com/rabbitmq/rabbitmq-server/issues/1001). The file must be readable by the RabbitMQ user and the node must be restarted. [There is no step 3](http://www.rabbitmq.com/plugins.html).

3.6.x has reached end of life last month and this plugin has been deprecated since 3.6.7 because it's not necessary any more and its downsides.

3.7.x provides a [built-in peer discovery mechanism](http://www.rabbitmq.com/cluster-formation.html) heavily influenced by this plugin.
